# This workflow is responsible for listening for the `/rebase` command in pull request comments.
# When a user with write permissions comments `/rebase`, this workflow will dispatch
# a `rebase-command` event, which will trigger the actual rebase workflow.
# This separation ensures that the rebase logic is only run when requested and authorized.

name: Slash Command Dispatcher

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          # This token is used to authenticate the action and dispatch the event.
          # The default GITHUB_TOKEN is sufficient for this purpose.
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Define the command we are listening for.
          commands: rebase
          
          # Set the required permission level for the user issuing the command.
          # 'write' permission is a safe level, allowing collaborators to use the command.
          permission: write
          
          # We only want this command to work on pull requests.
          issue-type: pull-request
          
          # The type of event to dispatch. This will trigger the rebase workflow.
          dispatch-type: repository
