name: Stale PR Notifier

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get recent commits from main
        id: get_commits
        run: |
          COMMITS=$(git log origin/main --pretty=format:'- %h %s' -n 5)
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check open PRs and notify if stale
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITS: ${{ steps.get_commits.outputs.commits }}
        run: |
          for pr_number in $(gh pr list --state open --json number -q '.[].number'); do
            echo "Checking PR number $pr_number"
            pr_branch=$(gh pr view $pr_number --json headRefName -q '.headRefName')
            git fetch origin $pr_branch
            
            if git merge-base --is-ancestor origin/main "origin/$pr_branch"; then
              echo "PR #$pr_number is up to date."
            else
              echo "PR #$pr_number is stale. Commenting."
              
              existing_comment=$(gh pr view $pr_number --json comments -q '.comments[] | select(.body | contains("This PR is out-of-date")) | .id')
              
              if [ -z "$existing_comment" ]; then
                BODY="⚠️ **This PR is out-of-date with the `main` branch.**

                The base branch has been updated with new changes.

                **Recent commits to `main`:**
                ```
                $COMMITS
                ```

                To ensure a clean merge, please rebase your branch on top of the latest `main` and push your changes."
                gh pr comment "$pr_number" --body "$BODY"
              else
                echo "A stale comment already exists on PR #$pr_number. Skipping."
              fi
            fi
          done
